/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  ITaskCreator,
  ITaskCreatorInterface,
} from "../../../contracts/interfaces/ITaskCreator";
import type { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";

const _abi = [
  {
    inputs: [],
    name: "cancelTask",
    outputs: [
      {
        internalType: "bool",
        name: "success",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "luckyNumber",
        type: "uint256",
      },
    ],
    name: "createTask",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ITaskCreator__factory {
  static readonly abi = _abi;
  static createInterface(): ITaskCreatorInterface {
    return new utils.Interface(_abi) as ITaskCreatorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITaskCreator {
    return new Contract(address, _abi, signerOrProvider) as ITaskCreator;
  }
}
